import os
import autogen
import autogen.runtime_logging
import pandas as pd
import sqlite3
import json
from autogen import AssistantAgent, UserProxyAgent, config_list_from_json


assistant_id = os.environ.get("ASSISTANT_ID", None)
config_list = config_list_from_json("C:/Users/rahul/Documents/OAI_CONFIG_LIST.json")
llm_config = {"config_list": config_list}


def subjective_agent(rubric):
    return autogen.AssistantAgent(
        name="S_clinician",
        system_message=f"You are a clinician who is going to generate the Subjective part of the SOAP Note of the conversation between the doctor(s) and the patient. Include information from the conversation according to the subjective section of the rubric:{rubric}",
        llm_config=llm_config
    )

def objective_agent(rubric):
    return autogen.AssistantAgent(
        name="O_clinician",
        system_message=f"You are a clinician who is going to generate the Objective part of the SOAP Note of the conversation between the doctor(s) and the patient. Include information from the conversation according to the objective section of the rubric:{rubric}",
        llm_config=llm_config
    )

def assessment_plan_agent(rubric):
    return autogen.AssistantAgent(
        name="AP_clinician",
        system_message=f"You are a clinician who is going to generate the Assessment and Plan part of the SOAP Note of the conversation between the doctor(s) and the patient. Include information from the conversation according to the assessment and plans sections of the rubric:{rubric}. Refer to the Subjective and Objective sections generated by the S_clinician and O_clinician while generating to ensure coherence.",
        llm_config=llm_config
    )



